### PR TITLE
Use install dir var when running install script

### PR DESCRIPTION
**Pull request by jakeisnt**

### CODE REVIEW

**Comment by teesloane** [comment]
Thanks for the PR. I'm not sure why I have either `default_install_dir` or `install_dir` when neither are being used. This is failing because GitHub Actions changed something on Linux machines recently, so once I fix this I'll merge this in.

**Comment by jakeisnt** [comment]
For sure! I've been trying to get this to build on my NixOS machine and was having some trouble because NixOS doesn't use /usr/local/bin for programs. Still trying to get Firn to build my site with GitHub actions

**Comment by teesloane** [comment]
This should work now if you pull master as I updated the GH action. As for NIxOS - I'm not sure how to handle installation -  but can you manually download the binary and move the file where needed with NixOS?

**Comment by tad-lispy** [comment]
Firn looks very nice. Thanks for your work!

@jakeisnt did you make it work on NixOS?

**Pull request closed without merging**
