### PR TITLE
Docs: proofread docs

### PR DESCRIPTION
**Pull request by yosevu**
Reading through the docs and proofreading as I go. This is as far as I got today.

Fix typos, syntax, and wording

- docs/backlinks.org
- docs/breadcrumbs.org
- docs/content.org
- docs/data-and-metadata.org
- docs/files-and-headlines.org
- docs/firn_tags.org
- docs/folding.org
- docs/table-of-contents.org

### CODE REVIEW

**Review by teesloane — APPROVED** [review]
This is amazing — thank you! Can I merge this or were you planning on pushing more changes to this PR?

**Comment by yosevu** [comment]
I'll finish proofreading when I can, so if it's alright to sit a day or two you can leave it. Otherwise I'll just create a separate PR.

**Comment by teesloane** [comment]
Ok. I'll leave it open for a few days; if you get around to it — great — if not, still great, and I'll merge it for the 0.0.10 release.

**Comment by teesloane** [comment]
Merged this as I'll be doing some doc work for the 0.0.10 release this week. Thanks again!

**Pull request merged**
