### PR TITLE
Using a sub-part of the generated HTML as the RSS description

### PR DESCRIPTION
**Pull request by lyderichti59**
Hi,

As discussed in the issue #89, I implemented a way to avoid the use of the whole HTML content of an article as the `<description>` of an article in the RSS feed.xml file.

Note : Instead of using the  `[:main]` tag as suggested by @teesloane in the issue, I extracted the first `[:article.rss]`.
It is discussable, but I think it fits well the semantic of a RSS article. Indeed, the main tag can contain other 'article-unrelated' nodes.
This is a breaking change for users that are currently using RSS.

Waiting for your opinion on this.

### CODE REVIEW

**Comment by teesloane** [comment]
I gave this a test and it worked great! I think it's ready to merge save for one thing to consider.  The binary has grown in size by about 6 mb, and I suspect that may be because the `hiccup-find` project has [clojurescript as a dependency](https://github.com/cjohansen/hiccup-find/blob/master/project.clj#L6-L7) and that might be being included in the final binary output. I could be wrong though, as I don't know the ins and out of how Clojure pulls dependencies into jars (or how GraalVM turns that into a binary for that matter).

Binary size isn't a terribly important thing for this project, but I don't like the idea of including unnecessary dependencies if I can avoid it (ie, clojurescript in this situation). I would be happy to merge this and then go in and cherry pick the functions we need from hiccup-find into the util namespace (and of which, the code should credit the work of the original author) and only use what we need.

Thoughts?

**Comment by lyderichti59** [comment]
Nice catch. Hmm, you are right. I don't like neither the fact to include clojurescript. If we include in Firn's repo only what's necessary, we still need 62 LOCs out of 92 total LOCs for the whole lib. I think we can afford the 30 LOCs left and include the whole file.

I guess it would be better to copy paste the whole source code of the `hiccup-find` lib under Firn repo's `/clojure/src/hiccup-find/core.clj` (and add credits) ?
Thus, we would keep the same namespaces, we would not alter the original source code, and we would not 'pollute' `firn.utils`.

**Comment by teesloane** [comment]
Sounds good - let's vendor the whole file and credit it (same as dirwatch.clj).

**Comment by lyderichti59** [comment]
Done :)

**Comment by teesloane** [comment]
Tested and good to go! Thanks for the contribution.

**Pull request merged**
